name: Build
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        options: ["", "ENABLE_OPENMP=1"]
    steps:
      - uses: actions/checkout@v3
      - run: make launch ${{ matrix.options }}

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        options: ["", "ENABLE_OPENMP=1"]
    steps:
      - uses: actions/checkout@v3
      - run: make launch CC=$(brew --prefix llvm@15)/bin/clang LDFLAGS+=-L$(brew --prefix libomp)/lib ${{ matrix.options }}

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        options: ["", "/openmp"]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cl /Zc:preprocessor /std:c11 /O2 /fp:fast ${{ matrix.options }} /Femain.exe *.c && ./main
