name: Build
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        options: ["", "ENABLE_OPENMP=1"]
    steps:
      - uses: actions/checkout@v3
      - run: make main ${{ matrix.options }}
      - run: ./main 1
      - run: ./main 4

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        options: ["", "ENABLE_OPENMP=1"]
    steps:
      - uses: actions/checkout@v3
      - run: make main CC=$(brew --prefix llvm@15)/bin/clang LDFLAGS+=-L$(brew --prefix libomp)/lib ${{ matrix.options }}
      - run: ./main 1
      - run: ./main 4

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        options: ["", "/openmp"]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - run: |
          mkdir include/external && curl https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -o include/external/stb_image.h
          cl /Iinclude /Zc:preprocessor /std:c11 /O2 /fp:fast ${{ matrix.options }} /Femain.exe src/*.c
      - run: ./main.exe 1
      - run: ./main.exe 4
