name: Build
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - run: make launch

  build-openmp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - run: make launch ENABLE_OPENMP=1

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cl /Zc:preprocessor /std:c11 /O2 /fp:fast /Femain.exe *.c && ./main

  build-openmp-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cl /Zc:preprocessor /std:c11 /O2 /fp:fast /openmp /Femain.exe *.c && ./main
